package org.sample;
// Generated Aug 18, 2012 10:02:34 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private Integer regno;
     private String name;
     private Integer age;

    public Student() {
    }

    public Student(String name, Integer age) {
       this.name = name;
       this.age = age;
    }
   
    public Integer getRegno() {
        return this.regno;
    }
    
    public void setRegno(Integer regno) {
        this.regno = regno;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    
}


